import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/.next/**',
      '**/dist/**',
      '**/build/**',
      '**/node_modules/**',
      '**/.venv/**',
      // Generated by `next build` and explicitly not to be edited. Its triple-slash
      // references are Next's own, so linting it reports errors nobody may fix.
      '**/next-env.d.ts',
      // Generated from contracts/schemas. Style is the generator's business; a
      // reproducibility check proves these match the schema.
      '**/src/generated/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'error',
    },
  },
  {
    // Build scripts run in Node, not the browser.
    files: ['**/*.mjs', '**/scripts/**/*.js'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        URL: 'readonly',
        __dirname: 'readonly',
      },
    },
  },
);
